/*
 * generated by Xtext 2.23.0
 */
package xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyUNOUiModule extends AbstractMyUNOUiModule {

	public MyUNOUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
