/*
 * generated by Xtext 2.23.0
 */
package xtext.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import projet_UNO.IDM.ui.internal.IDMActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyUNOExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(IDMActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		IDMActivator activator = IDMActivator.getInstance();
		return activator != null ? activator.getInjector(IDMActivator.XTEXT_MYUNO) : null;
	}

}
