/*
 * generated by Xtext 2.23.0
 */
package xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtext.parser.antlr.internal.InternalMyUNOParser;
import xtext.services.MyUNOGrammarAccess;

public class MyUNOParser extends AbstractAntlrParser {

	@Inject
	private MyUNOGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMyUNOParser createParser(XtextTokenStream stream) {
		return new InternalMyUNOParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Variante";
	}

	public MyUNOGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyUNOGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
