/*
 * generated by Xtext 2.23.0
 */
package xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyUNOScopeProvider extends DelegatingScopeProvider {
}
