/*
 * generated by Xtext 2.23.0
 */
package xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyUNOStandaloneSetup extends MyUNOStandaloneSetupGenerated {

	public static void doSetup() {
		new MyUNOStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
