/**
 * generated by Xtext 2.23.0
 */
package xtext.myUNO.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import xtext.myUNO.Gagnant;
import xtext.myUNO.MyUNOPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Gagnant</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.myUNO.impl.GagnantImpl#getNombre_de_manches_gagnees <em>Nombre de manches gagnees</em>}</li>
 *   <li>{@link xtext.myUNO.impl.GagnantImpl#getNombre <em>Nombre</em>}</li>
 *   <li>{@link xtext.myUNO.impl.GagnantImpl#getPoints <em>Points</em>}</li>
 *   <li>{@link xtext.myUNO.impl.GagnantImpl#getNombre_de_points <em>Nombre de points</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GagnantImpl extends MinimalEObjectImpl.Container implements Gagnant
{
  /**
   * The default value of the '{@link #getNombre_de_manches_gagnees() <em>Nombre de manches gagnees</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombre_de_manches_gagnees()
   * @generated
   * @ordered
   */
  protected static final String NOMBRE_DE_MANCHES_GAGNEES_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNombre_de_manches_gagnees() <em>Nombre de manches gagnees</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombre_de_manches_gagnees()
   * @generated
   * @ordered
   */
  protected String nombre_de_manches_gagnees = NOMBRE_DE_MANCHES_GAGNEES_EDEFAULT;

  /**
   * The default value of the '{@link #getNombre() <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombre()
   * @generated
   * @ordered
   */
  protected static final int NOMBRE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNombre() <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombre()
   * @generated
   * @ordered
   */
  protected int nombre = NOMBRE_EDEFAULT;

  /**
   * The default value of the '{@link #getPoints() <em>Points</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPoints()
   * @generated
   * @ordered
   */
  protected static final String POINTS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPoints() <em>Points</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPoints()
   * @generated
   * @ordered
   */
  protected String points = POINTS_EDEFAULT;

  /**
   * The default value of the '{@link #getNombre_de_points() <em>Nombre de points</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombre_de_points()
   * @generated
   * @ordered
   */
  protected static final int NOMBRE_DE_POINTS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNombre_de_points() <em>Nombre de points</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombre_de_points()
   * @generated
   * @ordered
   */
  protected int nombre_de_points = NOMBRE_DE_POINTS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GagnantImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyUNOPackage.Literals.GAGNANT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNombre_de_manches_gagnees()
  {
    return nombre_de_manches_gagnees;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNombre_de_manches_gagnees(String newNombre_de_manches_gagnees)
  {
    String oldNombre_de_manches_gagnees = nombre_de_manches_gagnees;
    nombre_de_manches_gagnees = newNombre_de_manches_gagnees;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUNOPackage.GAGNANT__NOMBRE_DE_MANCHES_GAGNEES, oldNombre_de_manches_gagnees, nombre_de_manches_gagnees));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNombre()
  {
    return nombre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNombre(int newNombre)
  {
    int oldNombre = nombre;
    nombre = newNombre;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUNOPackage.GAGNANT__NOMBRE, oldNombre, nombre));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPoints()
  {
    return points;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPoints(String newPoints)
  {
    String oldPoints = points;
    points = newPoints;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUNOPackage.GAGNANT__POINTS, oldPoints, points));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNombre_de_points()
  {
    return nombre_de_points;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNombre_de_points(int newNombre_de_points)
  {
    int oldNombre_de_points = nombre_de_points;
    nombre_de_points = newNombre_de_points;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUNOPackage.GAGNANT__NOMBRE_DE_POINTS, oldNombre_de_points, nombre_de_points));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyUNOPackage.GAGNANT__NOMBRE_DE_MANCHES_GAGNEES:
        return getNombre_de_manches_gagnees();
      case MyUNOPackage.GAGNANT__NOMBRE:
        return getNombre();
      case MyUNOPackage.GAGNANT__POINTS:
        return getPoints();
      case MyUNOPackage.GAGNANT__NOMBRE_DE_POINTS:
        return getNombre_de_points();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyUNOPackage.GAGNANT__NOMBRE_DE_MANCHES_GAGNEES:
        setNombre_de_manches_gagnees((String)newValue);
        return;
      case MyUNOPackage.GAGNANT__NOMBRE:
        setNombre((Integer)newValue);
        return;
      case MyUNOPackage.GAGNANT__POINTS:
        setPoints((String)newValue);
        return;
      case MyUNOPackage.GAGNANT__NOMBRE_DE_POINTS:
        setNombre_de_points((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyUNOPackage.GAGNANT__NOMBRE_DE_MANCHES_GAGNEES:
        setNombre_de_manches_gagnees(NOMBRE_DE_MANCHES_GAGNEES_EDEFAULT);
        return;
      case MyUNOPackage.GAGNANT__NOMBRE:
        setNombre(NOMBRE_EDEFAULT);
        return;
      case MyUNOPackage.GAGNANT__POINTS:
        setPoints(POINTS_EDEFAULT);
        return;
      case MyUNOPackage.GAGNANT__NOMBRE_DE_POINTS:
        setNombre_de_points(NOMBRE_DE_POINTS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyUNOPackage.GAGNANT__NOMBRE_DE_MANCHES_GAGNEES:
        return NOMBRE_DE_MANCHES_GAGNEES_EDEFAULT == null ? nombre_de_manches_gagnees != null : !NOMBRE_DE_MANCHES_GAGNEES_EDEFAULT.equals(nombre_de_manches_gagnees);
      case MyUNOPackage.GAGNANT__NOMBRE:
        return nombre != NOMBRE_EDEFAULT;
      case MyUNOPackage.GAGNANT__POINTS:
        return POINTS_EDEFAULT == null ? points != null : !POINTS_EDEFAULT.equals(points);
      case MyUNOPackage.GAGNANT__NOMBRE_DE_POINTS:
        return nombre_de_points != NOMBRE_DE_POINTS_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (nombre_de_manches_gagnees: ");
    result.append(nombre_de_manches_gagnees);
    result.append(", nombre: ");
    result.append(nombre);
    result.append(", points: ");
    result.append(points);
    result.append(", nombre_de_points: ");
    result.append(nombre_de_points);
    result.append(')');
    return result.toString();
  }

} //GagnantImpl
