/**
 * generated by Xtext 2.23.0
 */
package xtext.myUNO.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import xtext.myUNO.Final;
import xtext.myUNO.Initial;
import xtext.myUNO.Manche;
import xtext.myUNO.MyUNOPackage;
import xtext.myUNO.Variante;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Variante</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.myUNO.impl.VarianteImpl#getName <em>Name</em>}</li>
 *   <li>{@link xtext.myUNO.impl.VarianteImpl#getDebut <em>Debut</em>}</li>
 *   <li>{@link xtext.myUNO.impl.VarianteImpl#getManche <em>Manche</em>}</li>
 *   <li>{@link xtext.myUNO.impl.VarianteImpl#getFin <em>Fin</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VarianteImpl extends MinimalEObjectImpl.Container implements Variante
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getDebut() <em>Debut</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDebut()
   * @generated
   * @ordered
   */
  protected Initial debut;

  /**
   * The cached value of the '{@link #getManche() <em>Manche</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getManche()
   * @generated
   * @ordered
   */
  protected Manche manche;

  /**
   * The cached value of the '{@link #getFin() <em>Fin</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFin()
   * @generated
   * @ordered
   */
  protected Final fin;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VarianteImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyUNOPackage.Literals.VARIANTE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUNOPackage.VARIANTE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Initial getDebut()
  {
    return debut;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDebut(Initial newDebut, NotificationChain msgs)
  {
    Initial oldDebut = debut;
    debut = newDebut;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyUNOPackage.VARIANTE__DEBUT, oldDebut, newDebut);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDebut(Initial newDebut)
  {
    if (newDebut != debut)
    {
      NotificationChain msgs = null;
      if (debut != null)
        msgs = ((InternalEObject)debut).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyUNOPackage.VARIANTE__DEBUT, null, msgs);
      if (newDebut != null)
        msgs = ((InternalEObject)newDebut).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyUNOPackage.VARIANTE__DEBUT, null, msgs);
      msgs = basicSetDebut(newDebut, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUNOPackage.VARIANTE__DEBUT, newDebut, newDebut));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Manche getManche()
  {
    return manche;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetManche(Manche newManche, NotificationChain msgs)
  {
    Manche oldManche = manche;
    manche = newManche;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyUNOPackage.VARIANTE__MANCHE, oldManche, newManche);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setManche(Manche newManche)
  {
    if (newManche != manche)
    {
      NotificationChain msgs = null;
      if (manche != null)
        msgs = ((InternalEObject)manche).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyUNOPackage.VARIANTE__MANCHE, null, msgs);
      if (newManche != null)
        msgs = ((InternalEObject)newManche).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyUNOPackage.VARIANTE__MANCHE, null, msgs);
      msgs = basicSetManche(newManche, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUNOPackage.VARIANTE__MANCHE, newManche, newManche));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Final getFin()
  {
    return fin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFin(Final newFin, NotificationChain msgs)
  {
    Final oldFin = fin;
    fin = newFin;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyUNOPackage.VARIANTE__FIN, oldFin, newFin);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFin(Final newFin)
  {
    if (newFin != fin)
    {
      NotificationChain msgs = null;
      if (fin != null)
        msgs = ((InternalEObject)fin).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyUNOPackage.VARIANTE__FIN, null, msgs);
      if (newFin != null)
        msgs = ((InternalEObject)newFin).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyUNOPackage.VARIANTE__FIN, null, msgs);
      msgs = basicSetFin(newFin, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUNOPackage.VARIANTE__FIN, newFin, newFin));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyUNOPackage.VARIANTE__DEBUT:
        return basicSetDebut(null, msgs);
      case MyUNOPackage.VARIANTE__MANCHE:
        return basicSetManche(null, msgs);
      case MyUNOPackage.VARIANTE__FIN:
        return basicSetFin(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyUNOPackage.VARIANTE__NAME:
        return getName();
      case MyUNOPackage.VARIANTE__DEBUT:
        return getDebut();
      case MyUNOPackage.VARIANTE__MANCHE:
        return getManche();
      case MyUNOPackage.VARIANTE__FIN:
        return getFin();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyUNOPackage.VARIANTE__NAME:
        setName((String)newValue);
        return;
      case MyUNOPackage.VARIANTE__DEBUT:
        setDebut((Initial)newValue);
        return;
      case MyUNOPackage.VARIANTE__MANCHE:
        setManche((Manche)newValue);
        return;
      case MyUNOPackage.VARIANTE__FIN:
        setFin((Final)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyUNOPackage.VARIANTE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyUNOPackage.VARIANTE__DEBUT:
        setDebut((Initial)null);
        return;
      case MyUNOPackage.VARIANTE__MANCHE:
        setManche((Manche)null);
        return;
      case MyUNOPackage.VARIANTE__FIN:
        setFin((Final)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyUNOPackage.VARIANTE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyUNOPackage.VARIANTE__DEBUT:
        return debut != null;
      case MyUNOPackage.VARIANTE__MANCHE:
        return manche != null;
      case MyUNOPackage.VARIANTE__FIN:
        return fin != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //VarianteImpl
