/**
 * generated by Xtext 2.23.0
 */
package xtext.myUNO;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Final</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.myUNO.Final#getGagnant <em>Gagnant</em>}</li>
 * </ul>
 *
 * @see xtext.myUNO.MyUNOPackage#getFinal()
 * @model
 * @generated
 */
public interface Final extends EObject
{
  /**
   * Returns the value of the '<em><b>Gagnant</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gagnant</em>' containment reference.
   * @see #setGagnant(Gagnant)
   * @see xtext.myUNO.MyUNOPackage#getFinal_Gagnant()
   * @model containment="true"
   * @generated
   */
  Gagnant getGagnant();

  /**
   * Sets the value of the '{@link xtext.myUNO.Final#getGagnant <em>Gagnant</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gagnant</em>' containment reference.
   * @see #getGagnant()
   * @generated
   */
  void setGagnant(Gagnant value);

} // Final
