/**
 * generated by Xtext 2.23.0
 */
package xtext.myUNO;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gagnant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.myUNO.Gagnant#getNombre_de_manches_gagnees <em>Nombre de manches gagnees</em>}</li>
 *   <li>{@link xtext.myUNO.Gagnant#getNombre <em>Nombre</em>}</li>
 *   <li>{@link xtext.myUNO.Gagnant#getPoints <em>Points</em>}</li>
 *   <li>{@link xtext.myUNO.Gagnant#getNombre_de_points <em>Nombre de points</em>}</li>
 * </ul>
 *
 * @see xtext.myUNO.MyUNOPackage#getGagnant()
 * @model
 * @generated
 */
public interface Gagnant extends EObject
{
  /**
   * Returns the value of the '<em><b>Nombre de manches gagnees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre de manches gagnees</em>' attribute.
   * @see #setNombre_de_manches_gagnees(String)
   * @see xtext.myUNO.MyUNOPackage#getGagnant_Nombre_de_manches_gagnees()
   * @model
   * @generated
   */
  String getNombre_de_manches_gagnees();

  /**
   * Sets the value of the '{@link xtext.myUNO.Gagnant#getNombre_de_manches_gagnees <em>Nombre de manches gagnees</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nombre de manches gagnees</em>' attribute.
   * @see #getNombre_de_manches_gagnees()
   * @generated
   */
  void setNombre_de_manches_gagnees(String value);

  /**
   * Returns the value of the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre</em>' attribute.
   * @see #setNombre(int)
   * @see xtext.myUNO.MyUNOPackage#getGagnant_Nombre()
   * @model
   * @generated
   */
  int getNombre();

  /**
   * Sets the value of the '{@link xtext.myUNO.Gagnant#getNombre <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nombre</em>' attribute.
   * @see #getNombre()
   * @generated
   */
  void setNombre(int value);

  /**
   * Returns the value of the '<em><b>Points</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Points</em>' attribute.
   * @see #setPoints(String)
   * @see xtext.myUNO.MyUNOPackage#getGagnant_Points()
   * @model
   * @generated
   */
  String getPoints();

  /**
   * Sets the value of the '{@link xtext.myUNO.Gagnant#getPoints <em>Points</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Points</em>' attribute.
   * @see #getPoints()
   * @generated
   */
  void setPoints(String value);

  /**
   * Returns the value of the '<em><b>Nombre de points</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre de points</em>' attribute.
   * @see #setNombre_de_points(int)
   * @see xtext.myUNO.MyUNOPackage#getGagnant_Nombre_de_points()
   * @model
   * @generated
   */
  int getNombre_de_points();

  /**
   * Sets the value of the '{@link xtext.myUNO.Gagnant#getNombre_de_points <em>Nombre de points</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nombre de points</em>' attribute.
   * @see #getNombre_de_points()
   * @generated
   */
  void setNombre_de_points(int value);

} // Gagnant
