/**
 * generated by Xtext 2.23.0
 */
package xtext.myUNO;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Manche</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.myUNO.Manche#getTour <em>Tour</em>}</li>
 *   <li>{@link xtext.myUNO.Manche#getNombre_de_cartes <em>Nombre de cartes</em>}</li>
 *   <li>{@link xtext.myUNO.Manche#getCartes_par_tours <em>Cartes par tours</em>}</li>
 *   <li>{@link xtext.myUNO.Manche#getCarte_speciale <em>Carte speciale</em>}</li>
 *   <li>{@link xtext.myUNO.Manche#getContestation <em>Contestation</em>}</li>
 *   <li>{@link xtext.myUNO.Manche#getCondition <em>Condition</em>}</li>
 * </ul>
 *
 * @see xtext.myUNO.MyUNOPackage#getManche()
 * @model
 * @generated
 */
public interface Manche extends EObject
{
  /**
   * Returns the value of the '<em><b>Tour</b></em>' attribute.
   * The literals are from the enumeration {@link xtext.myUNO.Tour}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tour</em>' attribute.
   * @see xtext.myUNO.Tour
   * @see #setTour(Tour)
   * @see xtext.myUNO.MyUNOPackage#getManche_Tour()
   * @model
   * @generated
   */
  Tour getTour();

  /**
   * Sets the value of the '{@link xtext.myUNO.Manche#getTour <em>Tour</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tour</em>' attribute.
   * @see xtext.myUNO.Tour
   * @see #getTour()
   * @generated
   */
  void setTour(Tour value);

  /**
   * Returns the value of the '<em><b>Nombre de cartes</b></em>' attribute.
   * The literals are from the enumeration {@link xtext.myUNO.Nombre_de_cartes}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre de cartes</em>' attribute.
   * @see xtext.myUNO.Nombre_de_cartes
   * @see #setNombre_de_cartes(Nombre_de_cartes)
   * @see xtext.myUNO.MyUNOPackage#getManche_Nombre_de_cartes()
   * @model
   * @generated
   */
  Nombre_de_cartes getNombre_de_cartes();

  /**
   * Sets the value of the '{@link xtext.myUNO.Manche#getNombre_de_cartes <em>Nombre de cartes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nombre de cartes</em>' attribute.
   * @see xtext.myUNO.Nombre_de_cartes
   * @see #getNombre_de_cartes()
   * @generated
   */
  void setNombre_de_cartes(Nombre_de_cartes value);

  /**
   * Returns the value of the '<em><b>Cartes par tours</b></em>' attribute.
   * The literals are from the enumeration {@link xtext.myUNO.Cartes_par_tour}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cartes par tours</em>' attribute.
   * @see xtext.myUNO.Cartes_par_tour
   * @see #setCartes_par_tours(Cartes_par_tour)
   * @see xtext.myUNO.MyUNOPackage#getManche_Cartes_par_tours()
   * @model
   * @generated
   */
  Cartes_par_tour getCartes_par_tours();

  /**
   * Sets the value of the '{@link xtext.myUNO.Manche#getCartes_par_tours <em>Cartes par tours</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cartes par tours</em>' attribute.
   * @see xtext.myUNO.Cartes_par_tour
   * @see #getCartes_par_tours()
   * @generated
   */
  void setCartes_par_tours(Cartes_par_tour value);

  /**
   * Returns the value of the '<em><b>Carte speciale</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Carte speciale</em>' attribute.
   * @see #setCarte_speciale(String)
   * @see xtext.myUNO.MyUNOPackage#getManche_Carte_speciale()
   * @model
   * @generated
   */
  String getCarte_speciale();

  /**
   * Sets the value of the '{@link xtext.myUNO.Manche#getCarte_speciale <em>Carte speciale</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Carte speciale</em>' attribute.
   * @see #getCarte_speciale()
   * @generated
   */
  void setCarte_speciale(String value);

  /**
   * Returns the value of the '<em><b>Contestation</b></em>' attribute.
   * The literals are from the enumeration {@link xtext.myUNO.Contestation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contestation</em>' attribute.
   * @see xtext.myUNO.Contestation
   * @see #setContestation(Contestation)
   * @see xtext.myUNO.MyUNOPackage#getManche_Contestation()
   * @model
   * @generated
   */
  Contestation getContestation();

  /**
   * Sets the value of the '{@link xtext.myUNO.Manche#getContestation <em>Contestation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contestation</em>' attribute.
   * @see xtext.myUNO.Contestation
   * @see #getContestation()
   * @generated
   */
  void setContestation(Contestation value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' attribute.
   * @see #setCondition(String)
   * @see xtext.myUNO.MyUNOPackage#getManche_Condition()
   * @model
   * @generated
   */
  String getCondition();

  /**
   * Sets the value of the '{@link xtext.myUNO.Manche#getCondition <em>Condition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' attribute.
   * @see #getCondition()
   * @generated
   */
  void setCondition(String value);

} // Manche
