/**
 * generated by Xtext 2.23.0
 */
package xtext.myUNO;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Nombre de joueurs</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see xtext.myUNO.MyUNOPackage#getNombre_de_joueurs()
 * @model
 * @generated
 */
public enum Nombre_de_joueurs implements Enumerator
{
  /**
   * The '<em><b>Deux</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DEUX_VALUE
   * @generated
   * @ordered
   */
  DEUX(0, "deux", "2"),

  /**
   * The '<em><b>Plus que 2</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PLUS_QUE_2_VALUE
   * @generated
   * @ordered
   */
  PLUS_QUE_2(1, "plus_que_2", ">2");

  /**
   * The '<em><b>Deux</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DEUX
   * @model name="deux" literal="2"
   * @generated
   * @ordered
   */
  public static final int DEUX_VALUE = 0;

  /**
   * The '<em><b>Plus que 2</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PLUS_QUE_2
   * @model name="plus_que_2" literal="&gt;2"
   * @generated
   * @ordered
   */
  public static final int PLUS_QUE_2_VALUE = 1;

  /**
   * An array of all the '<em><b>Nombre de joueurs</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Nombre_de_joueurs[] VALUES_ARRAY =
    new Nombre_de_joueurs[]
    {
      DEUX,
      PLUS_QUE_2,
    };

  /**
   * A public read-only list of all the '<em><b>Nombre de joueurs</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Nombre_de_joueurs> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Nombre de joueurs</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Nombre_de_joueurs get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Nombre_de_joueurs result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Nombre de joueurs</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Nombre_de_joueurs getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Nombre_de_joueurs result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Nombre de joueurs</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Nombre_de_joueurs get(int value)
  {
    switch (value)
    {
      case DEUX_VALUE: return DEUX;
      case PLUS_QUE_2_VALUE: return PLUS_QUE_2;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Nombre_de_joueurs(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Nombre_de_joueurs
